# Site settings
title: HapiKit
description: > # this means to ignore newlines until "baseurl:"
  Tooling to build better HTTP API client libraries
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hapikit.github.io" # the base hostname & protocol for your site
github_username:  hapikit

# Build settings
markdown: kramdown
